export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const SET_REFRESH_TOKEN = 'SET_REFRESH_TOKEN';
export const AUTHENTICATE = 'AUTHENTICATE';
export const IS_AUTHENTICATING = 'IS_AUTHENTICATING';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
export const AUTHENTICATION_ERROR_MESSAGE = 'AUTHENTICATION_ERROR_MESSAGE';