export const SET_PROJECTS_BY_TEAMS = "SET_PROJECTS_BY_TEAMS";
export const SET_PROJECT = "SET_PROJECT";
export const SET_PROJECTS_BY_USER = "SET_PROJECTS_BY_USER";
export const GET_PROJECT = "GET_PROJECT";
export const GET_PROJECT_SECTIONS = "GET_PROJECT_SECTIONS";
export const GET_SECTION_CATEGORIES = "GET_SECTION_CATEGORIES";
export const GET_CATEGORY_ELEMENTS = "GET_CATEGORY_ELEMENTS"